services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - ENABLE_OLLAMA_API=true
      - ENABLE_OPENAI_API=false
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
      - DISABLE_STREAMING=true

    volumes:
      - open-webui-data:/app/backend/data

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs

  adapter:
    build: ./adapter
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "4000:4000"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - '--web.listen-address=0.0.0.0:9100'
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

  ollama-exporter:
    build: ./ollama-exporter
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana

volumes:
  open-webui-data:
